name: "build-tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build_eppp:
    name: Build
    strategy:
      matrix:
        idf_ver: ["latest", "release-v5.5", "release-v5.4", "release-v5.3"]
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout rdkafka repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build with IDF-${{ matrix.idf_ver }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          cd librdkafka/examples/producer/
          idf.py build
